name: Build, test, and deploy ASP.Net Core app to Azure Web App - BacklogrAPI

on:
  push:
    branches:
      - main
    paths:
      - 'Backlogr.Api/**'
      - 'Backlogr.Api.Tests/**'
      - '.github/workflows/main_backlograpi.yml'
  workflow_dispatch:

jobs:
  build_test_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore API
        run: dotnet restore ./Backlogr.Api/Backlogr.Api.csproj

      - name: Restore API tests
        run: dotnet restore ./Backlogr.Api.Tests/Backlogr.Api.Tests.csproj

      - name: Build API
        run: dotnet build ./Backlogr.Api/Backlogr.Api.csproj --configuration Release --no-restore

      - name: Run API tests
        run: dotnet test ./Backlogr.Api.Tests/Backlogr.Api.Tests.csproj --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ./Backlogr.Api/Backlogr.Api.csproj --configuration Release --output "${{ github.workspace }}/published-api" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backlogr-api
          path: ${{ github.workspace }}/published-api

  deploy:
    runs-on: ubuntu-latest
    needs: build_test_publish
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backlogr-api
          path: ./published-api

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DEDFF375DE1B480E95B45C1E9BD99F42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6F17A881292743108D2C32A5D9E88DCB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A46373CA73164B949CFCF2FA8E47F75D }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BacklogrAPI'
          slot-name: 'Production'
          package: ./published-api
